// Sea for Virtual Margate.
//
// Hand-written HLSL rather than Shader Graph: this is generated by tooling, and a
// .shadergraph is a large JSON graph that is painful to author or diff outside the
// editor. The trade-off is that a future URP upgrade may need a look here.
//
// Needs "Opaque Texture" and "Depth Texture" enabled on the URP asset -- refraction
// and the shoreline foam both read the scene behind the water.
Shader "Margate/Water"
{
    Properties
    {
        [Header(Colour)]
        _ShallowColor  ("Shallow",            Color) = (0.24, 0.55, 0.55, 1)
        _DeepColor     ("Deep",               Color) = (0.015, 0.10, 0.19, 1)
        _DepthFade     ("Depth fade (m)",     Float) = 5.0
        _Turbidity     ("Turbidity",          Range(0,1)) = 0.55

        [Header(Foam)]
        _FoamColor     ("Foam",               Color) = (0.95, 0.97, 0.97, 1)
        _FoamDepth     ("Foam depth (m)",     Float) = 1.1
        _FoamEdge      ("Foam edge (m)",      Float) = 0.18
        _FoamSpeed     ("Foam drift",         Float) = 0.10

        [Header(Surface)]
        _Smooth        ("Smoothness",         Range(0,1)) = 0.94
        _SpecPower     ("Glint tightness",    Float) = 500
        _SpecInt       ("Glint strength",     Float) = 4.0
        _FresnelPow    ("Fresnel power",      Float) = 5.0
        _ReflStrength  ("Sky reflection",     Range(0,1)) = 0.75
        _Refract       ("Refraction (m)",     Float) = 0.30

        [Header(Waves)]
        _WaveA         ("Wave A (dx,dz,steep,len)", Vector) = (1,    0.32, 0.16, 44)
        _WaveB         ("Wave B",                   Vector) = (0.72, 1,    0.11, 25)
        _WaveC         ("Wave C",                   Vector) = (-0.55,0.86, 0.08, 14)
        _WaveSpeed     ("Wave speed",         Float) = 0.85
        _RippleScale   ("Ripple scale",       Float) = 1.30
        _RippleStr     ("Ripple strength",    Float) = 0.30
        _Debug         ("Debug view",         Float) = 0
    }

    SubShader
    {
        Tags { "RenderType"="Transparent" "Queue"="Transparent" "RenderPipeline"="UniversalPipeline" }

        Pass
        {
            Name "ForwardLit"
            Tags { "LightMode"="UniversalForward" }
            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off
            Cull Back

            HLSLPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            #pragma target 3.0
            #pragma multi_compile_fragment _ _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_CASCADE
            #pragma multi_compile_fog

            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Core.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/Lighting.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareDepthTexture.hlsl"
            #include "Packages/com.unity.render-pipelines.universal/ShaderLibrary/DeclareOpaqueTexture.hlsl"

            CBUFFER_START(UnityPerMaterial)
                float4 _ShallowColor, _DeepColor, _FoamColor;
                float  _DepthFade, _Turbidity;
                float  _FoamDepth, _FoamEdge, _FoamSpeed;
                float  _Smooth, _SpecPower, _SpecInt, _FresnelPow, _ReflStrength, _Refract;
                float4 _WaveA, _WaveB, _WaveC;
                float  _WaveSpeed, _RippleScale, _RippleStr, _Debug;
            CBUFFER_END

            struct Attributes { float4 positionOS : POSITION; float4 color : COLOR; };
            struct Varyings
            {
                float4 positionCS : SV_POSITION;
                float3 positionWS : TEXCOORD0;
                float3 normalWS   : TEXCOORD1;
                float4 screenPos  : TEXCOORD2;
                float  fogCoord   : TEXCOORD3;
                float  shore      : TEXCOORD4;
            };

            // Standard Gerstner: circular particle motion, so crests sharpen and
            // troughs flatten the way real swell does. Accumulates the tangent frame
            // so the normal comes out analytically rather than from finite differences.
            float3 Gerstner(float4 wave, float3 p, inout float3 tang, inout float3 binm, float t)
            {
                float steep = wave.z;
                float len   = max(wave.w, 0.01);
                float k     = 6.28318530718 / len;
                float c     = sqrt(9.81 / k);            // deep-water phase speed
                float2 d    = normalize(wave.xy);
                float  f    = k * (dot(d, p.xz) - c * t);
                float  a    = steep / k;

                tang += float3(-d.x * d.x * (steep * sin(f)),
                                d.x        * (steep * cos(f)),
                               -d.x * d.y * (steep * sin(f)));
                binm += float3(-d.x * d.y * (steep * sin(f)),
                                d.y        * (steep * cos(f)),
                               -d.y * d.y * (steep * sin(f)));
                return float3(d.x * (a * cos(f)), a * sin(f), d.y * (a * cos(f)));
            }

            // Cheap procedural capillary detail -- four directional octaves, no texture.
            float3 RippleNormal(float2 p, float t)
            {
                float2 grad = 0;
                [unroll]
                for (int i = 0; i < 4; i++)
                {
                    float  ang  = 0.9 + i * 1.71;
                    float2 d    = float2(cos(ang), sin(ang));
                    float  freq = 0.55 * pow(1.9, i) * _RippleScale;
                    float  amp  = 0.55 / pow(1.9, i);
                    float  ph   = dot(p, d) * freq + t * (0.8 + i * 0.4);
                    grad += d * (cos(ph) * freq * amp);
                }
                return normalize(float3(-grad.x, 1.0, -grad.y));
            }

            Varyings vert(Attributes IN)
            {
                Varyings OUT;
                float3 posWS = TransformObjectToWorld(IN.positionOS.xyz);
                float  t     = _Time.y * _WaveSpeed;

                // Vertex colour R = normalised depth. Waves shoal: full swell in deep
                // water, flat at the waterline, so crests never wash over the sand.
                float shoal = smoothstep(0.05, 0.80, IN.color.r);

                // Fade swell out with distance. The detailed near tiles carry Gerstner
                // waves and the open-sea skirt is too coarse to resolve them, so without
                // this the boundary between them shows as a rectangle on the water.
                float dcam = distance(GetCameraPositionWS(), posWS);
                shoal *= saturate(1.0 - dcam / 700.0);

                float3 tang = float3(1, 0, 0), binm = float3(0, 0, 1);
                float3 disp = 0;
                disp += Gerstner(_WaveA, posWS, tang, binm, t);
                disp += Gerstner(_WaveB, posWS, tang, binm, t);
                disp += Gerstner(_WaveC, posWS, tang, binm, t);
                posWS += disp * shoal;
                tang = lerp(float3(1,0,0), tang, shoal);
                binm = lerp(float3(0,0,1), binm, shoal);
                OUT.shore = IN.color.r;

                OUT.positionWS = posWS;
                OUT.normalWS   = normalize(cross(binm, tang));
                OUT.positionCS = TransformWorldToHClip(posWS);
                OUT.screenPos  = ComputeScreenPos(OUT.positionCS);
                OUT.fogCoord   = ComputeFogFactor(OUT.positionCS.z);
                return OUT;
            }

            half4 frag(Varyings IN) : SV_Target
            {
                float2 screenUV = IN.screenPos.xy / max(IN.screenPos.w, 1e-5);
                float3 V = normalize(GetCameraPositionWS() - IN.positionWS);
                float  t = _Time.y * _WaveSpeed;

                // surface normal = swell + capillary detail
                // Fade the capillary detail out with distance. A 1 m ripple sampled at
                // 200 m is far below a pixel and turns into moire, which is what the
                // whole sea was doing.
                float camDist = distance(GetCameraPositionWS(), IN.positionWS);
                float detail  = saturate(1.0 - camDist / 350.0);
                float3 rip = RippleNormal(IN.positionWS.xz, t);
                float3 N   = normalize(IN.normalWS + float3(rip.x, 0, rip.z) * _RippleStr * detail);

                // --- how much water is between us and whatever is behind it -------
                float sceneEye = LinearEyeDepth(SampleSceneDepth(screenUV), _ZBufferParams);
                float surfEye  = IN.screenPos.w;
                float waterDepth = max(sceneEye - surfEye, 0);

                if (_Debug > 0.5)
                {
                    // 1 = scene eye depth /500, 2 = water depth /20, 3 = raw depth sample
                    if (_Debug < 1.5) return half4(sceneEye.xxx / 500.0, 1);
                    if (_Debug < 2.5) return half4(waterDepth.xxx / 20.0, 1);
                    return half4(SampleSceneDepth(screenUV).xxx, 1);
                }

                // --- refraction: nudge the sample by the surface normal, but reject
                //     samples that turn out to be IN FRONT of the water, or the beach
                //     bleeds over the sea at grazing angles.
                float2 offs   = N.xz * _Refract / max(surfEye, 1.0);
                float2 refrUV = screenUV + offs;
                float  refrEye = LinearEyeDepth(SampleSceneDepth(refrUV), _ZBufferParams);
                if (refrEye < surfEye) { refrUV = screenUV; refrEye = sceneEye; }
                float3 behind = SampleSceneColor(refrUV);
                float  refrDepth = max(refrEye - surfEye, 0);

                // --- body colour: Beer-Lambert-ish extinction with depth ----------
                float  fade  = saturate(refrDepth / max(_DepthFade, 0.01));
                float3 water = lerp(_ShallowColor.rgb, _DeepColor.rgb, fade);
                float  clarity = saturate(exp(-refrDepth * (0.25 + _Turbidity)));
                float3 col = lerp(water, behind * water * 1.6, clarity * (1.0 - _Turbidity * 0.55));

                // --- sky reflection + fresnel -------------------------------------
                float3 R = reflect(-V, N);
                float3 sky = GlossyEnvironmentReflection(R, IN.positionWS, 1.0 - _Smooth, 1.0, screenUV);
                float  fres = pow(1.0 - saturate(dot(N, V)), _FresnelPow);
                col = lerp(col, sky, saturate(fres * _ReflStrength + 0.02));

                // --- sun glint ----------------------------------------------------
                Light main = GetMainLight();
                float3 H = normalize(main.direction + V);
                float spec = pow(saturate(dot(N, H)), _SpecPower) * _SpecInt;
                col += main.color * spec;

                // --- shoreline foam ------------------------------------------------
                float shore = 1.0 - saturate(waterDepth / max(_FoamDepth, 0.01));
                float wob = sin(IN.positionWS.x * 0.35 + t * 1.7)
                          * sin(IN.positionWS.z * 0.31 - t * 1.3) * 0.5 + 0.5;
                float foam = smoothstep(0.45, 0.95, shore * (0.65 + 0.5 * wob));
                foam += smoothstep(0.92, 1.0, shore);              // hard line at the waterline
                col = lerp(col, _FoamColor.rgb, saturate(foam));

                // opaque at the shore so foam is solid, translucent in deep water
                float alpha = saturate(0.55 + fade * 0.45 + foam) * smoothstep(0.0, 0.06, IN.shore);
                col = MixFog(col, IN.fogCoord);
                return half4(col, alpha);
            }
            ENDHLSL
        }
    }
    FallBack "Universal Render Pipeline/Lit"
}
